
spring:
  application:
    # 指定application name
    name: auth2
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
server:
  port: 8061
max-http-header-size: 65536
security:
  basic:
    enabled=false:
